northwind:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 172.19.0.1
      user: postgres
      password: postgres
      port: 5432
      dbname: northwind
      schema: "development"
      threads: 4
      connect_timeout: 10
    prod:
      type: postgres
      host: 172.19.0.1
      user: postgres
      password: postgres
      port: 5432
      dbname: northwind
      schema: "analytics"
      threads: 4
      connect_timeout: 10
